// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tallerV1.Data;

#nullable disable

namespace tallerV1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251201171716_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tallerV1.Models.Entities.Bodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Bodegas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 12, 1, 11, 17, 16, 352, DateTimeKind.Local).AddTicks(6368),
                            Nombre = "San Ignacio"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 12, 1, 11, 17, 16, 352, DateTimeKind.Local).AddTicks(6369),
                            Nombre = "Mirador"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 12, 1, 11, 17, 16, 352, DateTimeKind.Local).AddTicks(6371),
                            Nombre = "Bonanza"
                        });
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RUC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 12, 1, 11, 17, 16, 352, DateTimeKind.Local).AddTicks(6253),
                            Nombre = "Top Green S.A"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 12, 1, 11, 17, 16, 352, DateTimeKind.Local).AddTicks(6254),
                            Nombre = "Tecnología Agrícola S.A"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            FechaCreacion = new DateTime(2025, 12, 1, 11, 17, 16, 352, DateTimeKind.Local).AddTicks(6256),
                            Nombre = "Servicios Agrícolas del Pacífico"
                        });
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("AnioFabricacion")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoMantenimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GalonesPorHora")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("GalonesPorKm")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("HorasActuales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KilometrajeActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Placa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TipoControl")
                        .HasColumnType("int");

                    b.Property<int>("TipoEquipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.HistorialEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialEquipos");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.MantenimientoPreventivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IntervaloDias")
                        .HasColumnType("int");

                    b.Property<decimal?>("IntervaloHoras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IntervaloKilometros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("NotificacionEnviada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProximaFecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ProximasHoras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProximoKilometraje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoControl")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaFecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UltimasHoras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UltimoKilometraje")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("MantenimientosPreventivos");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.MantenimientoPreventivoTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MantenimientoPreventivoId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MantenimientoPreventivoId");

                    b.ToTable("MantenimientosPreventivosTareas");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RepuestoId")
                        .HasColumnType("int");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("int");

                    b.Property<int>("StockNuevo")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RepuestoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnviadaPorEmail")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLeida")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoNotificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.OrdenTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CostoManoObra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoRepuestos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoServiciosExternos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescripcionProblema")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DiagnosticoTecnico")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HorasHombre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HorometroEquipo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KilometrajeEquipo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObservacionesFinales")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("TipoMantenimiento")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioAprobadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioAsignadoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("NumeroOrden")
                        .IsUnique();

                    b.HasIndex("UsuarioAprobadorId");

                    b.HasIndex("UsuarioAsignadoId");

                    b.HasIndex("UsuarioCreadorId");

                    b.ToTable("OrdenesTrabajo");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.OrdenTrabajoImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoImagen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTrabajoId");

                    b.ToTable("OrdenesTrabajoImagenes");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.OrdenTrabajoRepuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaInstalacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RepuestoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("RepuestoId");

                    b.ToTable("OrdenesTrabajoRepuestos");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Repuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("BodegaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MesesGarantia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMaximo")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BodegaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@taller.com",
                            EmpresaId = 1,
                            FechaCreacion = new DateTime(2025, 12, 1, 11, 17, 16, 456, DateTimeKind.Local).AddTicks(3046),
                            NombreCompleto = "Administrador del Sistema",
                            PasswordHash = "$2a$11$uD4ZHvm19cWNCFSocthxEuadtAnBF2bf044eDxNTisadfzRFb..xK",
                            Rol = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Equipo", b =>
                {
                    b.HasOne("tallerV1.Models.Entities.Empresa", "Empresa")
                        .WithMany("Equipos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.HistorialEquipo", b =>
                {
                    b.HasOne("tallerV1.Models.Entities.Equipo", "Equipo")
                        .WithMany("HistorialEquipos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tallerV1.Models.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany()
                        .HasForeignKey("OrdenTrabajoId");

                    b.HasOne("tallerV1.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.MantenimientoPreventivo", b =>
                {
                    b.HasOne("tallerV1.Models.Entities.Equipo", "Equipo")
                        .WithMany("MantenimientosPreventivos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.MantenimientoPreventivoTarea", b =>
                {
                    b.HasOne("tallerV1.Models.Entities.MantenimientoPreventivo", "MantenimientoPreventivo")
                        .WithMany("Tareas")
                        .HasForeignKey("MantenimientoPreventivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MantenimientoPreventivo");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.MovimientoInventario", b =>
                {
                    b.HasOne("tallerV1.Models.Entities.Repuesto", "Repuesto")
                        .WithMany("MovimientosInventario")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tallerV1.Models.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repuesto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Notificacion", b =>
                {
                    b.HasOne("tallerV1.Models.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany()
                        .HasForeignKey("OrdenTrabajoId");

                    b.HasOne("tallerV1.Models.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.OrdenTrabajo", b =>
                {
                    b.HasOne("tallerV1.Models.Entities.Equipo", "Equipo")
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tallerV1.Models.Entities.Usuario", "UsuarioAprobador")
                        .WithMany()
                        .HasForeignKey("UsuarioAprobadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tallerV1.Models.Entities.Usuario", "UsuarioAsignado")
                        .WithMany("OrdenesAsignadas")
                        .HasForeignKey("UsuarioAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tallerV1.Models.Entities.Usuario", "UsuarioCreador")
                        .WithMany("OrdenesCreadas")
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("UsuarioAprobador");

                    b.Navigation("UsuarioAsignado");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.OrdenTrabajoImagen", b =>
                {
                    b.HasOne("tallerV1.Models.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Imagenes")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.OrdenTrabajoRepuesto", b =>
                {
                    b.HasOne("tallerV1.Models.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Repuestos")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tallerV1.Models.Entities.Repuesto", "Repuesto")
                        .WithMany("OrdenesTrabajoRepuestos")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Repuesto", b =>
                {
                    b.HasOne("tallerV1.Models.Entities.Bodega", "Bodega")
                        .WithMany("Repuestos")
                        .HasForeignKey("BodegaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bodega");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Usuario", b =>
                {
                    b.HasOne("tallerV1.Models.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Bodega", b =>
                {
                    b.Navigation("Repuestos");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Empresa", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Equipo", b =>
                {
                    b.Navigation("HistorialEquipos");

                    b.Navigation("MantenimientosPreventivos");

                    b.Navigation("OrdenesTrabajo");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.MantenimientoPreventivo", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.OrdenTrabajo", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("Repuestos");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Repuesto", b =>
                {
                    b.Navigation("MovimientosInventario");

                    b.Navigation("OrdenesTrabajoRepuestos");
                });

            modelBuilder.Entity("tallerV1.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("OrdenesAsignadas");

                    b.Navigation("OrdenesCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
